title: "Amruta Gandhe"
description: >-
  Data Analytics & BI | Data Strategy & Omnichannel Insights
baseurl: "" # for user site like username.github.io
url: "https://amrutag7.github.io"

# Theme settings
remote_theme: "mmistakes/minimal-mistakes"

# Navigation bar
header_pages:
  - index.md
  - about.md
  - projects.md
  - contact.md
  
footer_include: footer_custom.html

rss:
  enabled: false
  
plugins:
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge
