title: "Amruta Gandhe"
description: >-
  Data Analytics & BI | Data Strategy & Omnichannel Insights
baseurl: "" # for user site like username.github.io
url: "https://amrutag7.github.io"

rss:
  enabled: false

show_theme_credit: false
